# # Dockerfile.api --Dockerfile for API Server (json-server)
# FROM node:16
# WORKDIR /app
# COPY db.json .
# RUN npm install -g json-server
# EXPOSE 3000
# CMD ["json-server", "--watch", "db.json", "--port", "3000"]


FROM node:20
WORKDIR /app
COPY db.json .
RUN npm install -g json-server
EXPOSE 3000
CMD ["json-server", "--watch", "db.json", "--port", "3000", "--host", "0.0.0.0"]